build(repo): Update to Node 20

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -81,7 +81,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [ 18, 19 ]
+        node-version: [ 18, 20 ]
 
     steps:
       - name: Checkout Repo
@@ -167,7 +167,7 @@ jobs:
 
       - name: Publish to Verdaccio
         run: |
-          if [ \"$(npm config get registry)\" = \"https://registry.npmjs.org/\" ]; then echo 'Error: Using default registry' && exit 1; npm run build -- ${{ env.TURBO_ARGS }} && changeset publish --no-git-tag; fi",
+          if [ \"$(npm config get registry)\" = \"https://registry.npmjs.org/\" ]; then echo 'Error: Using default registry' && exit 1; else npm run build -- ${{ env.TURBO_ARGS }} && changeset publish --no-git-tag; fi",
 
       - name: Install @clerk/backend in /integration
         working-directory: ./integration
