feat(ci): Use @integration tag for verdaccio publishing
In certain cases, the published versions in verdaccio didnt  match the version ranges requested by the e2e template apps. Our verdaccio config allows proxying to npm so that some suites can install prev pkg versions (v4) so instead of falling completely, the apps were installing npm versions instead of the local ones.
During the cicd setup step, versioning runs before publishing so verdaccio gets the new versions. Some templates require previous version ranges and because of the npm-pass-through config we use, they get the live pkgs and not the local ones
To fix the above and make the whole flow more predictable, I introduced a integration tag. All local pkgs get published to @integration in verdaccio and the e2e templates can now request @integration instead of @latest or @5 - @integration ensures that they get the verdaccio version no matter the semver range

- Enhanced the `linkPackage` function to accept an optional tag parameter for better package linking.
- Updated integration presets to use the new `linkPackage` functionality, ensuring dependencies are linked correctly for integration testing.
- Added new environment variable support in the `mergeEnvVarsWithParams` function for improved configuration options.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -404,7 +404,8 @@ jobs:
         uses: ./.github/actions/verdaccio
         with:
           publish-cmd: |
-            if [ "$(pnpm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else CLERK_USE_RQ=${{ matrix.clerk-use-rq }} pnpm turbo build $TURBO_ARGS --only && pnpm changeset publish --no-git-tag; fi
+            if [ "$(pnpm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else CLERK_USE_RQ=${{ matrix.clerk-use-rq }} pnpm turbo build $TURBO_ARGS --only && pnpm changeset publish --no-git-tag --tag integration; fi
+
 
       - name: Edit .npmrc [link-workspace-packages=false]
         run: sed -i -E 's/link-workspace-packages=(deep|true)/link-workspace-packages=false/' .npmrc
