chore(repo): Re-introduce follow-on jobs to CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,7 +30,7 @@ jobs:
           show-progress: false
 
       - name: Setup
-        timeout-minutes: ${{ vars.TIMEOUT_MINUTES_SHORT }}
+        timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_SHORT) }}
         id: config
         uses: ./.github/actions/init
         with:
@@ -79,89 +79,89 @@ jobs:
           path: .turbo/runs
           retention-days: 1
 
-  # unit-tests:
-  #   name: Unit Tests
-  #   needs: formatting-linting
-  #   runs-on: ${{ vars.RUNNER_LARGE }}
-  #   timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_NORMAL) }}
+  unit-tests:
+    name: Unit Tests
+    needs: formatting-linting
+    runs-on: ${{ vars.RUNNER_LARGE }}
+    timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_NORMAL) }}
 
-  #   strategy:
-  #     matrix:
-  #       node-version: [ 18, 20 ]
+    strategy:
+      matrix:
+        node-version: [ 18, 20 ]
 
-  #   steps:
-  #     - name: Checkout Repo
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         show-progress: false
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          show-progress: false
 
-  #     - name: Setup
-  #       id: config
-  #       uses: ./.github/actions/init
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
-  #         turbo-team: ${{ vars.TURBO_TEAM }}
-  #         turbo-token: ${{ secrets.TURBO_TOKEN }}
+      - name: Setup
+        id: config
+        uses: ./.github/actions/init
+        with:
+          node-version: ${{ matrix.node-version }}
+          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
+          turbo-team: ${{ vars.TURBO_TEAM }}
+          turbo-token: ${{ secrets.TURBO_TOKEN }}
 
-  #     - name: Run tests
-  #       run: npx turbo test $TURBO_ARGS
-  #       env:
-  #         NODE_VERSION: ${{ matrix.node-version }}
+      - name: Run tests
+        run: npx turbo test $TURBO_ARGS
+        env:
+          NODE_VERSION: ${{ matrix.node-version }}
 
-  # integration-tests:
-  #   name: Integration Tests
-  #   needs: formatting-linting
-  #   runs-on: ${{ vars.RUNNER_LARGE }}
-  #   timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_NORMAL) }}
+  integration-tests:
+    name: Integration Tests
+    needs: formatting-linting
+    runs-on: ${{ vars.RUNNER_LARGE }}
+    timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_NORMAL) }}
 
-  #   strategy:
-  #     matrix:
-  #       test-name: [ 'generic', 'nextjs', 'remix' ]
+    strategy:
+      matrix:
+        test-name: [ 'generic', 'nextjs', 'remix' ]
 
-  #   steps:
-  #     - name: Checkout Repo
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         show-progress: false
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          show-progress: false
 
-  #     - name: Setup
-  #       id: config
-  #       uses: ./.github/actions/init
-  #       with:
-  #         turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
-  #         turbo-team: ${{ vars.TURBO_TEAM }}
-  #         turbo-token: ${{ secrets.TURBO_TOKEN }}
-  #         playwright-enabled: true
+      - name: Setup
+        id: config
+        uses: ./.github/actions/init
+        with:
+          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
+          turbo-team: ${{ vars.TURBO_TEAM }}
+          turbo-token: ${{ secrets.TURBO_TOKEN }}
+          playwright-enabled: true
 
-  #     - name: Verdaccio
-  #       uses: ./.github/actions/verdaccio
-  #       with:
-  #         publish-cmd: |
-  #           if [ "$(npm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else npx turbo build $TURBO_ARGS && npx changeset publish --no-git-tag; fi
+      - name: Verdaccio
+        uses: ./.github/actions/verdaccio
+        with:
+          publish-cmd: |
+            if [ "$(npm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else npx turbo build $TURBO_ARGS && npx changeset publish --no-git-tag; fi
 
-  #     - name: Install @clerk/backend in /integration
-  #       working-directory: ./integration
-  #       run: npm init -y && npm install @clerk/backend
+      - name: Install @clerk/backend in /integration
+        working-directory: ./integration
+        run: npm init -y && npm install @clerk/backend
 
-  #     - name: Install @clerk/clerk-js in os temp
-  #       working-directory: ${{runner.temp}}
-  #       run: mkdir clerk-js && cd clerk-js && npm init -y && npm install @clerk/clerk-js
+      - name: Install @clerk/clerk-js in os temp
+        working-directory: ${{runner.temp}}
+        run: mkdir clerk-js && cd clerk-js && npm init -y && npm install @clerk/clerk-js
 
-  #     - name: Run Integration Tests
-  #       run: npm run test:integration:${{ matrix.test-name }}
-  #       env:
-  #         E2E_APP_CLERK_JS_DIR: ${{runner.temp}}
-  #         E2E_CLERK_VERSION: 'latest'
-  #         INTEGRATION_INSTANCE_KEYS: ${{ secrets.INTEGRATION_INSTANCE_KEYS }}
-  #         MAILSAC_API_KEY: ${{ secrets.MAILSAC_API_KEY }}
+      - name: Run Integration Tests
+        run: npm run test:integration:${{ matrix.test-name }}
+        env:
+          E2E_APP_CLERK_JS_DIR: ${{runner.temp}}
+          E2E_CLERK_VERSION: 'latest'
+          INTEGRATION_INSTANCE_KEYS: ${{ secrets.INTEGRATION_INSTANCE_KEYS }}
+          MAILSAC_API_KEY: ${{ secrets.MAILSAC_API_KEY }}
 
-  #     # - name: Upload Integration Report for ${{ matrix.test-name }}
-  #     #   uses: actions/upload-artifact@v3
-  #     #   if: always()
-  #     #   with:
-  #     #     name: integration-report-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.test-name }}
-  #     #     path: playwright-report/
-  #     #     retention-days: 1
+      # - name: Upload Integration Report for ${{ matrix.test-name }}
+      #   uses: actions/upload-artifact@v3
+      #   if: always()
+      #   with:
+      #     name: integration-report-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.test-name }}
+      #     path: playwright-report/
+      #     retention-days: 1
