fix(repo): Retheme node_modules cache (#2351)
* fix(repo): Retheme node_modules cache

* fix(*): Apply `$TURBO_ARGS` to retheme

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,11 +58,11 @@ jobs:
 
       - name: Lint types using attw
         timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_SHORT) }}
-        run: npx turbo lint:attw --filter=!nextjs --only
+        run: npx turbo lint:attw $TURBO_ARGS --filter=!nextjs --only
 
       - name: Lint types using attw [Errors Allowed]
         timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_SHORT) }}
-        run: npx turbo lint:attw --filter=nextjs --continue --only
+        run: npx turbo lint:attw $TURBO_ARGS --filter=nextjs --continue --only
         continue-on-error: true  # TODO: Remove this when all related errors are fixed
 
       - name: Run lint
@@ -152,7 +152,7 @@ jobs:
         uses: ./.github/actions/verdaccio
         with:
           publish-cmd: |
-            if [ "$(npm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else npx turbo build $TURBO_ARGS && npx changeset publish --no-git-tag; fi
+            if [ "$(npm config get registry)" = "https://registry.npmjs.org/" ]; then echo 'Error: Using default registry' && exit 1; else npx turbo build $TURBO_ARGS --only && npx changeset publish --no-git-tag; fi
 
       - name: Install @clerk/backend in /integration
         working-directory: ./integration
